### ISSUE TITLE
not compatible with PHP < 5.5

### ISSUE THREAD

**Issue by Lightnicus** [silverstripe-australia/silverstripe-addressable#38]
Addressable.php line 70:

        if (!empty($customRegex = Config::inst()->get('Addressable', 'set_postcode_regex'))) {

having an expression in empty() is not supported by PHP less than 5.5:
Prior to PHP 5.5, empty() only supports variables; anything else will result in a parse error. In other words, the following will not work: empty(trim($name)). Instead, use trim($name) == false. 

Can you divide this into tow lines please?

**Comment by quamsta** [comment]
Also having this issue on PHP 5.3 (I know, I know), broke a resource site that I'm currently working on.

**Comment by stephenmcm** [comment]
I'd recommend setting you're composer requirements to '1.1.x' or similar to work around this for now. Using dev-master when not doing active development is generally discouraged.

**Comment by nyeholt** [comment]
Have committed a fix on the fly, is someone able to test I haven't completely broken things though? :dancer:
